export {default as About} from './About'
export {default as Contact} from './Contact'
export {default as Home} from './Home'
export {default as Menu} from './Menu'
export {default as NavBar} from './NavBar'
export {default as AnimateRoutes} from './AnimateRoutes'